name: test-b1

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo Running $GITHUB_REF

    - name: Push to ghpages
      run: |
        git clone --quiet --branch gh-pages --depth 1 git@github.com:ckaestne/test-action.git .gh-pages
        cd .gh-pages
        git rm -rf b1
        mkdir -p b1
        cp ../README.md b1/README.md
        git add b1
        git commit --allow-empty -m "Update pages for b1"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}       
        directory: '.gh-pages'
        branch: 'gh-pages'
        force: true 
      

        
